version: "3.5"

services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      # - "13000:80"
      - "13000:443"
    # volumes:
    #   - ./docker/nginx/server.conf:/etc/nginx/conf.d/servers.conf
    environment:
      TZ: "Asia/Tokyo"
  mysql:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASS:-pass}
      MYSQL_USER: ${DBUSER:-user}
      MYSQL_PASSWORD: ${DBPASS:-pass}
      MYSQL_DATABASE: test
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/server.conf:/etc/mysql/conf.d/my.cnf"
      - "./store/mysql:/var/lib/mysql"
  redis:
    restart: always
    image: redis:3.2-alpine
    ports:
      - '6379:6379'
  python:
    build: ./docker/python
    image: "my/python:latest"
    stdin_open: true
    ports:
      - '18888:8888'
    volumes:
      - ./workspace:/workspace
